version = 0.1

[default.global.parameters]
stack_name = "weather-data-pipeline-dev"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
